only_rules:
  - colon
  - comma
  - comment_spacing
  - duplicate_imports
  - leading_whitespace
  - mark
  - no_space_in_method_call
  - opening_brace
  - return_arrow_whitespace
  - statement_position
  - sorted_imports
  - custom_rules

custom_rules:
  no_too_many_blank_lines:
    name: "No too many blank lines"
    regex: '((?:\s*\n){4,})'
    message: "There are too many blank lines"
    severity: error

  input_line_break_under_class_struct_enum:
    name: "Input line break under class, struct, enum"
    regex: '(?-s)(class|struct|enum)\s(?!func|var).*\{\n.*[^\s]+'
    message: "Class, Struct, Enum must be followed by a single line."
    severity: error

